# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.3 13d6f1d"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "order-book-contract"
template_type = "Rust"

[[contracts]]
name = "liquidity-lock-script"
template_type = "Rust"

[[contracts]]
name = "info-lock-script"
template_type = "Rust"

[[contracts]]
name = "liquidity-type-script"
template_type = "Rust"
