name: Build and test

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-09-28
          override: true

      - uses: docker-practice/actions-setup-docker@master
        with:
          docker_channel: nightly
          # this value please see https://github.com/AkihiroSuda/moby-snapshot/releases
          docker_nightly_version: snapshot-20201008

      - name: Init submodules
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update -r --init

      - name: Install moleculec
        run: |
          cargo install moleculec

      - name: Install Capsule
        run: |
          mkdir -p ./capsule && curl -L https://github.com/nervosnetwork/capsule/releases/download/v0.4.3/capsule_v0.4.3_x86_64-linux.tar.gz | tar xvz -C ./capsule --strip-components=1
          chmod +x ./capsule/capsule

      - name: Build Contract
        run: make build

      - name: Test Contract
        run: make test
